# Configuration file

# Absolute WESAD dataset path
dataset_path: 'C:\Users\vgvau\PycharmProjects\IDC6940_RandomForest\windowed_outputs'

# Processing
multithread: false

# Participants
composite_participants: false # using all participants to train model (NOT default and has limitations)
participants: ["S4"]#, "S3"] # array of participants to predict for

# Variables
variables: {
      ECG: ["HR", "HRV"]
}

# ARIMA parameters, if all are NONE, parameters will be selected using AutoARIMA()
p: 5
d: 0
q: 0
